package main

import (
	"errors"
)

func commandMap(config *Config) error {
	data := &AutoGenerated{}
	var err error
	if config.NextPage == "" {
		config.NextPage = "https://pokeapi.co/api/v2/location"
	}
	data, err = getLocations(config.NextPage)
	if err != nil {
		return err
	}
	printLocations(data)
	updatePrevNext(data, config)
	return nil
}


func commandMapB(config *Config) error {
	data := &AutoGenerated{}
	var err error
	if config.PrevPage != "" {
		data, err = getLocations(config.PrevPage)
		if err != nil {
			return err
		}
	} else {
		return errors.New("no previous page")
	}
	printLocations(data)
	updatePrevNext(data, config)
	return nil
}